import { Ingredient } from "../redux/features/mealSlice";

export const MOCKED_INGREDIENTS: Ingredient[] = [
  {
    id: 1,
    name: "Peito de Frango",
    unit: "g",
    proteins: 0.2955,
    carbs: 0,
    fats: 0.0772,
    calories: 1.95,
  },
  {
    id: 2,
    name: "Macarrão",
    unit: "g",
    proteins: 0.0515,
    carbs: 0.2493,
    fats: 0.0105,
    calories: 1.31,
  },
  {
    id: 3,
    name: "Leite Integral",
    unit: "g",
    proteins: 0.031,
    carbs: 0.048,
    fats: 0.03,
    calories: 0.59,
  },
  {
    id: 4,
    name: "Aveia",
    unit: "g",
    proteins: 0.1689,
    carbs: 0.6627,
    fats: 0.069,
    calories: 3.89,
  },
  {
    id: 5,
    name: "Pão (1 fatia)",
    unit: "unidade",
    proteins: 1.99,
    carbs: 13.16,
    fats: 0.86,
    calories: 69,
  },
  {
    id: 6,
    name: "Banana",
    unit: "g",
    proteins: 0.01,
    carbs: 0.23,
    fats: 0,
    calories: 0.89,
  },
  {
    id: 7,
    name: "Iogurte",
    unit: "g",
    proteins: 0.0398,
    carbs: 0.1864,
    fats: 0.0115,
    calories: 0.99,
  },
  {
    id: 8,
    name: "Sucrilhos",
    unit: "g",
    proteins: 0.04,
    carbs: 0.866,
    fats: 0,
    calories: 3.8,
  },
  {
    id: 9,
    name: "Abacate",
    unit: "g",
    proteins: 0.02,
    carbs: 0.085,
    fats: 0.145,
    calories: 1.6,
  },
  {
    id: 10,
    name: "Doce de Leite",
    unit: "g",
    proteins: 0.028,
    carbs: 0.36,
    fats: 0.107,
    calories: 1.14,
  },
  {
    id: 11,
    name: "Ovo (1 unidade)",
    unit: "unidade",
    proteins: 6.3,
    carbs: 0.5,
    fats: 5.3,
    calories: 77,
  },
  {
    id: 12,
    name: "Feijão",
    unit: "g",
    proteins: 0,
    carbs: 0,
    fats: 0,
    calories: 0,
  },
  {
    id: 13,
    name: "Vegetais",
    unit: "g",
    proteins: 0,
    carbs: 0,
    fats: 0,
    calories: 0,
  },
];
